### ISSUE TITLE
The inaccuracy in readme

### ISSUE THREAD

**Issue by kai66673** [w0rp/dqt#13]
now:
git clone git@github.com:w0rp/dsmoke.git
git clone git@github.com:w0rp/dstruct.git
git clone git@github.com:w0rp/dqt.git

should be (in my opiniion):
git clone https://github.com/w0rp/dsmoke.git
git clone https://github.com/w0rp/dstruct.git
git clone https://github.com/w0rp/dqt.git

**Comment by w0rp** [comment]
The former connects via SSH, and the latter via HTTP. You can use either really, the latter will just prevent you from pushing, should you have access to do so.

**Comment by kai66673** [comment]
Maybe I'm wrong. However, the first option leads to 'permission denied' for me.
