### ISSUE TITLE
Resolving depencies in Ubuntu

### ISSUE THREAD

**Issue by kai66673** [w0rp/dqt#14]
just install smokeqt...:
sudo apt-get install smokeqt*

**Comment by w0rp** [comment]
There are a few packages in apt, but I'm not sure what version of Qt they support.

**Comment by kai66673** [comment]
(K)ububtu 14.04: Qt 4.8.6

**Comment by w0rp** [comment]
`smokeqt` isn't available on Linux Mint for some reason, but `libsmokeqtgui4-3 libsmokeqt4-dev libsmokeqt4-dbg libsmokeqtcore4-3` should provide everything needed across Debian, Ubuntu, and Linux Mint, so I'll add that to the readme.

**Comment by kai66673** [comment]
smokeqt is not package, just substring for apt )
